### PR TITLE
fix: doc comment on Role variant crashes macro

### LINKED ISSUE #28: Comments on AccessControlRole enum variants not working
Currently, adding a comment to a variant on an enum decorated with `AccessControlRole` fails.
Docs line should be ignored and left in place in case documentation is built from the code.

Example:

```rs
#[derive(AccessControlRole, Deserialize, Serialize, Copy, Clone)]
#[serde(crate = "near_sdk::serde")]
pub enum AclRole {
    /// Allows user to update the token binary that will be deployed for new tokens.
    TokenBinaryUpdater,
    /// Allows user to update the account id that will be used for new deployed tokens.
    TokenControllerUpdater,
}
```

Error:

```rs
error: expected identifier, found `#`
  --> near-token-factory/src/lib.rs:34:5
   |
34 |     /// Allows user to update the token binary that will be deployed for new tokens.
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier

error: expected identifier, found `#`
  --> near-token-factory/src/lib.rs:36:5
   |
36 |     /// Allows user to update the account id that will be used for new deployed tokens.
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier

error: proc-macro derive produced unparseable tokens
  --> near-token-factory/src/lib.rs:31:10
   |
31 | #[derive(AccessControlRole, Deserialize, Serialize, Copy, Clone)]
   |          ^^^^^^^^^^^^^^^^^

error: could not compile `near-token-factory` due to 3 previous errors
```

### PR DESCRIPTION
**Pull request by mooori**
Closes #28

### CODE REVIEW

File: near-plugins-derive/src/access_control_role.rs [hunk 1]
```diff
@@ -58,10 +58,10 @@ pub fn derive_access_control_role(input: TokenStream) -> TokenStream {
         ident, variants, ..
     } = input;
 
-    let variants = variants.into_iter().collect::<Vec<_>>();
+    let variant_idents = variants.into_iter().map(|v| v.ident).collect::<Vec<_>>();
```
Comment (mooori) [inline near-plugins-derive/src/access_control_role.rs:61]: It was a bug to _not_ do `map(|v| v.ident)`. The test contract used only plain variants like `LevelA` without comments, data or custom discriminants, which prevented the bug from surfacing.

File: near-plugins/tests/contracts/access_controllable/src/lib.rs [hunk 2]
```diff
@@ -4,11 +4,15 @@ use near_sdk::serde::{Deserialize, Serialize};
...
 
+/// Roles are represented by enum variants.
 #[derive(AccessControlRole, Deserialize, Serialize, Copy, Clone)]
 #[serde(crate = "near_sdk::serde")]
 pub enum Role {
+    /// Represents LevelA.
     LevelA,
+    /// Represents LevelB.
     LevelB,
+    /// Represents LevelC.
```
Comment (mooori) [inline near-plugins/tests/contracts/access_controllable/src/lib.rs:15]: Adding not-so-meaningful comments to show it's now working and to avoid regressions.

Comment (sept-en) [reply near-plugins/tests/contracts/access_controllable/src/lib.rs:15]: Just a note, we can add these comments in an enum in some of the examples to test the regression.

**Review by sept-en — APPROVED** [review]
LGTM!

**Review by mrLSD — APPROVED** [review]
