### PR TITLE
fix: Change hash encoding, support passing in `code` without borsh

### LINKED ISSUE #150: Fix the mess in the upgrade process
- [ ] The `up_staged_code_hash` returns array instead of base58 string.
- [ ] The `up_stage_code` accepts the binary in borsh instead of the raw file.
- [ ] The base64 is used instead of base58 to hash the code

### PR DESCRIPTION
**Pull request by r-near**
- Changes encoding of code hashes from base64 to bs58 in the Upgradable plugin
- Modifies `up_staged_code_hash()` return type from `Option<CryptoHash>` to `Option<String>` and updates all hash generation/comparison code accordingly
- Tests updated to match the new encoding.
- Support passing in `code` directly instead of with Borsh

Closes #150

### CODE REVIEW

**Comment by karim-en** [comment]
@r-near can you please bump the rust in seperate PR, because probably this PR will be cherry picked

File: near-plugins-derive/src/upgradable.rs [hunk 1]
```diff
@@ -165,14 +165,28 @@ pub fn derive_upgradable(input: TokenStream) -> TokenStream {
...
-                if code.is_empty() {
-                    ::near_sdk::env::storage_remove(self.up_storage_key(__UpgradableStorageKey::Code).as_ref());
-                    ::near_sdk::env::storage_remove(self.up_storage_key(__UpgradableStorageKey::StagingTimestamp).as_ref());
-                } else {
-                    let timestamp = ::near_sdk::env::block_timestamp() + self.up_get_duration(__UpgradableStorageKey::StagingDuration).unwrap_or(0);
-                    self.up_storage_write(__UpgradableStorageKey::Code, &code);
-                    self.up_set_timestamp(__UpgradableStorageKey::StagingTimestamp, timestamp);
+            fn up_stage_code(&mut self) {
+                match ::near_sdk::env::input() {
+                    None => {
```
Comment (karim-en) [inline near-plugins-derive/src/upgradable.rs:170]: Let's remove this branch, and just use unwarp_or_default

**Review by karim-en — CHANGES_REQUESTED** [review]

File: near-plugins-derive/src/upgradable.rs [hunk 2]
```diff
@@ -165,25 +165,33 @@ pub fn derive_upgradable(input: TokenStream) -> TokenStream {
...
+                let code = ::near_sdk::env::input().unwrap_or_default();
+
                 if code.is_empty() {
                     ::near_sdk::env::storage_remove(self.up_storage_key(__UpgradableStorageKey::Code).as_ref());
                     ::near_sdk::env::storage_remove(self.up_storage_key(__UpgradableStorageKey::StagingTimestamp).as_ref());
                 } else {
-                    let timestamp = ::near_sdk::env::block_timestamp() + self.up_get_duration(__UpgradableStorageKey::StagingDuration).unwrap_or(0);
+                    // Calculate timestamp more safely with checked_add to prevent overflow
+                    let duration = self.up_get_duration(__UpgradableStorageKey::StagingDuration).unwrap_or(0);
+                    let timestamp = match ::near_sdk::env::block_timestamp().checked_add(duration) {
```
Comment (karim-en) [inline near-plugins-derive/src/upgradable.rs:177]: No needs to complicate it match, saturating_add should be enough.

**Review by karim-en — CHANGES_REQUESTED** [review]

**Review by karim-en — APPROVED** [review]

File: near-plugins-derive/src/upgradable.rs [hunk 3]
```diff
@@ -165,25 +165,30 @@ pub fn derive_upgradable(input: TokenStream) -> TokenStream {
...
+            fn up_stage_code(&mut self) {
+                let code = ::near_sdk::env::input().unwrap_or_default();
+
                 if code.is_empty() {
                     ::near_sdk::env::storage_remove(self.up_storage_key(__UpgradableStorageKey::Code).as_ref());
                     ::near_sdk::env::storage_remove(self.up_storage_key(__UpgradableStorageKey::StagingTimestamp).as_ref());
                 } else {
-                    let timestamp = ::near_sdk::env::block_timestamp() + self.up_get_duration(__UpgradableStorageKey::StagingDuration).unwrap_or(0);
+                    // Use saturating_add to prevent overflow
+                    let duration = self.up_get_duration(__UpgradableStorageKey::StagingDuration).unwrap_or(0);
```
Comment (frolvanya) [inline near-plugins-derive/src/upgradable.rs:176]: can be replaced with `unwrap_or_default()` for readability

File: near-plugins-derive/src/upgradable.rs [hunk 4]
```diff
@@ -165,25 +165,30 @@ pub fn derive_upgradable(input: TokenStream) -> TokenStream {
...
             #[result_serializer(borsh)]
             fn up_staged_code(&self) -> Option<Vec<u8>> {
                 ::near_sdk::env::storage_read(self.up_storage_key(__UpgradableStorageKey::Code).as_ref())
             }
 
-            fn up_staged_code_hash(&self) -> Option<::near_sdk::CryptoHash> {
+            fn up_staged_code_hash(&self) -> Option<String> {
                 self.up_staged_code()
-                    .map(|code| Self::up_hash_code(code.as_ref()))
+                    .map(|code| ::near_sdk::bs58::encode(Self::up_hash_code(code.as_ref())).into_string())
```
Comment (frolvanya) [inline near-plugins-derive/src/upgradable.rs:191]: can we use `convert_code_to_crypto_hash` method here?

File: near-plugins-derive/src/upgradable.rs [hunk 5]
```diff
@@ -202,7 +207,7 @@ pub fn derive_upgradable(input: TokenStream) -> TokenStream {
                 }
 
                 let code = self.up_staged_code().unwrap_or_else(|| ::near_sdk::env::panic_str("Upgradable: No staged code"));
-                let expected_hash = ::near_sdk::base64::encode(Self::up_hash_code(code.as_ref()));
+                let expected_hash = ::near_sdk::bs58::encode(Self::up_hash_code(code.as_ref())).into_string();
```
Comment (frolvanya) [inline near-plugins-derive/src/upgradable.rs:210]: same question

**Review by frolvanya — APPROVED** [review]

File: near-plugins-derive/src/upgradable.rs (hunk 4 above)
Comment (frolvanya) [reply near-plugins-derive/src/upgradable.rs:191]: Oh, I forgot to check the function's location)

**Review by karim-en — APPROVED** [review]

File: near-plugins-derive/tests/upgradable.rs [hunk 6]
```diff
@@ -203,19 +203,17 @@ impl Setup {
     }
 }
 
-/// Panics if the conversion fails.
-fn convert_code_to_crypto_hash(code: &[u8]) -> CryptoHash {
-    near_sdk::env::sha256(code)
-        .try_into()
-        .expect("Code should be converted to CryptoHash")
+/// Converts code to a base58-encoded CryptoHash string.
+fn convert_code_to_crypto_hash(code: &[u8]) -> String {
```
Comment (olga24912) [inline near-plugins-derive/tests/upgradable.rs:207]: This is not crypto_hash; right now, we are returning CryptoHash. It's not very important, but maybe we could rename it to convert_code_to_bs58_encoded_hash or something like that?

Comment (karim-en) [reply near-plugins-derive/tests/upgradable.rs:207]: cc @r-near

**Review by olga24912 — APPROVED** [review]
